project:
  type: book
  output-dir: ../_site/portfoliooptimization

book:
  title: "Portfolio Optimization"
  author: "Muhamad Mustain"
  date: "01/03/2026"
  site-url: "https://muhamadmusta.in/book/portfoliooptimization"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    base-url: /portfolioop
  pdf:
    documentclass: scrreprt



