project:
  type: book
  output-dir: ../_site/newbookname

book:
  title: New Book Name
  site-url: https://muhamadmusta.in/book/newbookname
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo