project:
  type: book
  output-dir: ../_site/loremipsum

book:
  title: Lorem Ipsum
  site-url: https://muhamadmusta.in/book/loremipsum
  chapters:
    - index.qmd
    - walkthrough.qmd
    - part: section-one/index.qmd
      chapters:
        - section-one/intro.qmd
        - section-one/details.qmd
    - part: section-two/index.qmd
      chapters:
        - section-two/intro.qmd
        - section-two/details.qmd

number-sections: true
number-depth: 3

format:
  html:
    theme: cosmo