project:
  type: book
  output-dir: ../_site/loremipsum

book:
  title: "Belajar Statistika"
  author: "Muhamad Mustain"
  cover-image: cover.png
  site-url: https://muhamadmusta.in/book/loremipsum
  repo-url: https://github.com/musmeong/digital_book_resource/tree/main/loremipsum
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  page-footer: 
    left: "Copyright 2026, Muhamad Mustain"
    right: 
      - icon: github
        href: https://github.com/musmeong
  chapters:
    - index.qmd
    - preface.qmd
    - walkthrough.qmd
    - part: section-one/index.qmd
      chapters:
        - section-one/intro.qmd
        - section-one/details.qmd
    - part: section-two/index.qmd
      chapters:
        - section-two/intro.qmd
        - section-two/details.qmd

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    code-fold: true
    code-summary: "Show the code"